FROM node:14.0-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV PORT 80
EXPOSE $PORT
VOLUME ["/app/data"]
CMD ["npm", "start"]

# docker build -f Dockerfile.dev -t client-timer .
# run-dev: docker run -d -p 80:3000 -v "/home/user/Projects/time-organizer-v2/client:/app" -v /app/node_modules -v data:/app/data --name timer-app client-timer